[build]
  command = "yarn run build"

[build.environment]
  NODE_VERSION = "8.9.0"


# Tease unfound episodes
[[redirects]]
  from = "/episode/*"
  to = "/episode-not-found/index.html"
  status = 404

# Default to the home page as a 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
